# install kubernetes on centos
# http://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/ 
---
- name: install kubernetes
  hosts: kubernetes
  sudo: True
  
  tasks:
    - name: check linux flavour
      assert: { that: "ansible_os_family == 'RedHat'" }         
    - name: add master to hosts file
      lineinfile:
        dest=/etc/hosts
        state=present
        regexp='centos-master'
        line='{{ master_ip }}   centos-master'
    - name: add minion to hosts file
      lineinfile:
        dest=/etc/hosts
        state=present
        regexp='centos-minion'
        line='{{ minion_ip }}   centos-minion'
    - name: add docker repo
      copy: src=files/virt7-docker-common-release.repo dest=/etc/yum.repos.d/virt7-docker-common-release.repo
    - name: install kub
      yum: name=kubernetes,etcd state=present enablerepo=virt7-docker-common-release
    - name: copy kubernetes config
      copy: src=files/kubernetes-config dest=/etc/kubernetes/config backup=yes
    - name: disable firewall
      ignore_errors: yes
      service: name={{ item }} enabled=no state=stopped
      with_items:
        - iptables
        - firewalld
      
- name: master tasks
  hosts: centos-master
  sudo: True
  tasks:
    - name: copy etcd.conf
      copy: src=files/etcd.conf dest=/etc/etcd/etcd.conf backup=yes
      register: masteretcd
    - name: copy apiserver
      copy: src=files/apiserver dest=/etc/kubernetes/apiserver backup=yes
      register: masterapiserver
    - name: restart master services
      service: name={{ item }} state=restarted
      with_items:
        - etcd
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler
      when: masteretcd.changed or masterapiserver.changed
    - name: enable master services
      service: name={{ item }} enabled=yes
      with_items:
        - etcd
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler

- name: minion tasks
  hosts: centos-minion
  sudo: True
  tasks:
    - name: copy kubelet
      copy: src=files/kubelet dest=/etc/kubernetes/kubelet backup=yes
      register: minionkubelet
    - name: restart minion services
      service: name={{ item }} state=restarted
      with_items:
        - kube-proxy
        - kubelet
        - docker
      when: minionkubelet.changed
    - name: enable minion services
      service: name={{ item }} enabled=yes
      with_items:
        - kube-proxy
        - kubelet
        - docker
